### ISSUE TITLE
AS A surveyor I WANT to identify the OSM road link marching the OS road link in a small area SO THAT later on I'll find the directions mismatches

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/roads#16]
It is done on a small area: probably 1km^2. 

- [ ] import OS data into JSON and 4326
- [ ] import OSM data into JSON and 4326
- [ ] for each road segment: find OSM using name filter,  bb (coordinates) filter, any other filter ?
- [ ] output result 
- [ ] test / mesure results

**Comment by sebastianovide** [comment]
63% of OS roads have 1 road match. Tested on a couple of samples. They match.
